CREATE OR REPLACE FUNCTION FC_AUDITA_PARTICIPANTE()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO TA_AUDITORIA_LOG_PARTICIPANTE (
      TP_OPERACAO,
      ID_PARTICIPANTE,
      NM_PARTICIPANTE_NEW,
      DS_EMAIL_NEW,
      ID_TP_CATEGORIA_NEW
    ) VALUES (
      'I',
      NEW.ID_PARTICIPANTE,
      NEW.NM_PARTICIPANTE,
      NEW.DS_EMAIL,
      NEW.ID_TP_CATEGORIA
    );

  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO TA_AUDITORIA_LOG_PARTICIPANTE (
      TP_OPERACAO,
      ID_PARTICIPANTE,
      NM_PARTICIPANTE_OLD,
      DS_EMAIL_OLD,
      ID_TP_CATEGORIA_OLD,
      NM_PARTICIPANTE_NEW,
      DS_EMAIL_NEW,
      ID_TP_CATEGORIA_NEW
    ) VALUES (
      'U',
      OLD.ID_PARTICIPANTE,
      OLD.NM_PARTICIPANTE,
      OLD.DS_EMAIL,
      OLD.ID_TP_CATEGORIA,
      NEW.NM_PARTICIPANTE,
      NEW.DS_EMAIL,
      NEW.ID_TP_CATEGORIA
    );
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
