CREATE TABLE TA_AUDITORIA_LOG_PARTICIPANTE (
  ID_LOG SERIAL PRIMARY KEY,
  TP_OPERACAO CHAR(1) NOT NULL, -- I, U
  DT_OPERACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  NM_USUARIO_BD VARCHAR(100) DEFAULT SESSION_USER,
  NM_TERMINAL VARCHAR(100) DEFAULT inet_client_addr(),
  ID_PARTICIPANTE INTEGER,
  NM_PARTICIPANTE_OLD VARCHAR(100),
  DS_EMAIL_OLD VARCHAR(100),
  ID_TP_CATEGORIA_OLD INTEGER,
  NM_PARTICIPANTE_NEW VARCHAR(100),
  DS_EMAIL_NEW VARCHAR(100),
  ID_TP_CATEGORIA_NEW INTEGER
);
