CREATE TABLE TB_TP_ATIVIDADE (
  ID_TP_ATIVIDADE INTEGER GENERATED ALWAYS AS IDENTITY,
  DS_TP_ATIVIDADE VARCHAR(30) NOT NULL,
  CONSTRAINT PK_TB_TP_ATIVIDADE PRIMARY KEY (ID_TP_ATIVIDADE),
  CONSTRAINT UK_TB_TP_ATIV_DS UNIQUE (DS_TP_ATIVIDADE)
);

CREATE TABLE TB_TP_CATEGORIA (
  ID_TP_CATEGORIA INTEGER GENERATED ALWAYS AS IDENTITY,
  DS_TP_CATEGORIA VARCHAR(20) NOT NULL,
  CONSTRAINT PK_TB_TP_CATEGORIA PRIMARY KEY (ID_TP_CATEGORIA),
  CONSTRAINT UK_TB_TP_CAT_DS UNIQUE (DS_TP_CATEGORIA)
);

CREATE TABLE TB_TP_PARCEIRO (
  ID_TP_PARCEIRO INTEGER GENERATED ALWAYS AS IDENTITY,
  DS_TP_PARCEIRO VARCHAR(30) NOT NULL,
  CONSTRAINT PK_TB_TP_PARCEIRO PRIMARY KEY (ID_TP_PARCEIRO),
  CONSTRAINT UK_TB_TP_PARCE_DS UNIQUE (DS_TP_PARCEIRO)
);

CREATE TABLE TB_ATIVIDADE (
  ID_ATIVIDADE INTEGER GENERATED ALWAYS AS IDENTITY,
  DS_TITULO VARCHAR(100) NOT NULL,
  DT_INICIO TIMESTAMP NOT NULL,
  DT_FIM TIMESTAMP NOT NULL,
  ID_TP_ATIVIDADE INTEGER NOT NULL,
  DS_LOCAL VARCHAR(100),
  CONSTRAINT PK_TB_ATIVIDADE PRIMARY KEY (ID_ATIVIDADE),
  CONSTRAINT FK_TB_ATIVIDADE_TP FOREIGN KEY (ID_TP_ATIVIDADE)
    REFERENCES TB_TP_ATIVIDADE (ID_TP_ATIVIDADE),
  CONSTRAINT CK_TB_ATIVIDADE_DATAS CHECK (DT_FIM > DT_INICIO)
);

CREATE TABLE TB_PARTICIPANTE (
  ID_PARTICIPANTE INTEGER GENERATED ALWAYS AS IDENTITY,
  NM_PARTICIPANTE VARCHAR(100) NOT NULL,
  DS_EMAIL VARCHAR(100) NOT NULL,
  ID_TP_CATEGORIA INTEGER NOT NULL,
  CONSTRAINT PK_TB_PARTICIPANTE PRIMARY KEY (ID_PARTICIPANTE),
  CONSTRAINT UK_TB_PARTICIPANTE_EMAIL UNIQUE (DS_EMAIL),
  CONSTRAINT FK_TB_PARTICIPANTE_TP FOREIGN KEY (ID_TP_CATEGORIA)
    REFERENCES TB_TP_CATEGORIA (ID_TP_CATEGORIA)
);

CREATE TABLE TB_INSTRUTOR (
  ID_INSTRUTOR INTEGER GENERATED ALWAYS AS IDENTITY,
  NM_INSTRUTOR VARCHAR(100) NOT NULL,
  DS_AFILIACAO VARCHAR(100),
  DS_ESPECIALIDADE VARCHAR(100),
  CONSTRAINT PK_TB_INSTRUTOR PRIMARY KEY (ID_INSTRUTOR)
);

CREATE TABLE TB_PARCEIRO (
  ID_PARCEIRO INTEGER GENERATED ALWAYS AS IDENTITY,
  NM_PARCEIRO VARCHAR(100) NOT NULL,
  ID_TP_PARCEIRO INTEGER NOT NULL,
  VL_CONTRIBUICAO DECIMAL(10,2),
  CONSTRAINT PK_TB_PARCEIRO PRIMARY KEY (ID_PARCEIRO),
  CONSTRAINT FK_TB_PARCEIRO_TP FOREIGN KEY (ID_TP_PARCEIRO)
    REFERENCES TB_TP_PARCEIRO (ID_TP_PARCEIRO)
);

CREATE TABLE TB_CERTIFICADO (
  ID_CERTIFICADO INTEGER GENERATED ALWAYS AS IDENTITY,
  CD_HASH VARCHAR(64) NOT NULL,
  DT_EMISSAO DATE NOT NULL,
  ID_ATIVIDADE INTEGER NOT NULL,
  ID_PARTICIPANTE INTEGER NOT NULL,
  CONSTRAINT PK_TB_CERTIFICADO PRIMARY KEY (ID_CERTIFICADO),
  CONSTRAINT UK_TB_CERTIFICADO_HASH UNIQUE (CD_HASH),
  CONSTRAINT FK_TB_CERT_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE)
    REFERENCES TB_ATIVIDADE (ID_ATIVIDADE),
  CONSTRAINT FK_TB_CERT_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE)
    REFERENCES TB_PARTICIPANTE (ID_PARTICIPANTE)
);

CREATE TABLE TP_NOTA (
  CD_NOTA INTEGER PRIMARY KEY,
  DS_NOTA VARCHAR(20) NOT NULL,
  CONSTRAINT UK_TP_NOTA_DESCRICAO UNIQUE (DS_NOTA)
);

CREATE TABLE TB_FEEDBACK (
  ID_FEEDBACK INTEGER GENERATED ALWAYS AS IDENTITY,
  CD_NOTA INTEGER NOT NULL,
  DS_COMENTARIO TEXT,
  ID_ATIVIDADE INTEGER NOT NULL,
  ID_PARTICIPANTE INTEGER NOT NULL,
  CONSTRAINT PK_TB_FEEDBACK PRIMARY KEY (ID_FEEDBACK),
  CONSTRAINT FK_TB_FB_TP_NOTA FOREIGN KEY (CD_NOTA)
    REFERENCES TP_NOTA(CD_NOTA),
  CONSTRAINT FK_TB_FB_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE)
    REFERENCES TB_ATIVIDADE (ID_ATIVIDADE),
  CONSTRAINT FK_TB_FB_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE)
    REFERENCES TB_PARTICIPANTE (ID_PARTICIPANTE)
);

CREATE TABLE RL_ATIVIDADE_PARTICIPANTE (
  ID_ATIVIDADE INTEGER NOT NULL,
  ID_PARTICIPANTE INTEGER NOT NULL,
  DT_INSCRICAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_PRESENCA BOOLEAN DEFAULT FALSE,
  CONSTRAINT PK_RL_ATIV_PARTICIPANTE PRIMARY KEY (ID_ATIVIDADE, ID_PARTICIPANTE),
  CONSTRAINT FK_RL_AP_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE)
    REFERENCES TB_ATIVIDADE (ID_ATIVIDADE),
  CONSTRAINT FK_RL_AP_PARTICIPANTE FOREIGN KEY (ID_PARTICIPANTE)
    REFERENCES TB_PARTICIPANTE (ID_PARTICIPANTE)
);

CREATE TABLE RL_ATIVIDADE_INSTRUTOR (
  ID_ATIVIDADE INTEGER NOT NULL,
  ID_INSTRUTOR INTEGER NOT NULL,
  DS_PAPEL VARCHAR(30),
  CONSTRAINT PK_RL_ATIV_INSTRUTOR PRIMARY KEY (ID_ATIVIDADE, ID_INSTRUTOR),
  CONSTRAINT FK_RL_AI_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE)
    REFERENCES TB_ATIVIDADE (ID_ATIVIDADE),
  CONSTRAINT FK_RL_AI_INSTRUTOR FOREIGN KEY (ID_INSTRUTOR)
    REFERENCES TB_INSTRUTOR (ID_INSTRUTOR)
);

CREATE TABLE RL_ATIVIDADE_PARCEIRO (
  ID_ATIVIDADE INTEGER NOT NULL,
  ID_PARCEIRO INTEGER NOT NULL,
  VL_CONTRIBUICAO DECIMAL(10,2),
  CONSTRAINT PK_RL_ATIV_PARCEIRO PRIMARY KEY (ID_ATIVIDADE, ID_PARCEIRO),
  CONSTRAINT FK_RL_APAR_ATIVIDADE FOREIGN KEY (ID_ATIVIDADE)
    REFERENCES TB_ATIVIDADE (ID_ATIVIDADE),
  CONSTRAINT FK_RL_APAR_PARCEIRO FOREIGN KEY (ID_PARCEIRO)
    REFERENCES TB_PARCEIRO (ID_PARCEIRO)
);
