TRUNCATE TABLE
  RL_ATIVIDADE_PARCEIRO,
  RL_ATIVIDADE_PARTICIPANTE,
  RL_ATIVIDADE_INSTRUTOR,
  TB_FEEDBACK,
  TB_CERTIFICADO,
  TB_PARCEIRO,
  TB_INSTRUTOR,
  TB_PARTICIPANTE,
  TB_ATIVIDADE,
  TB_TP_PARCEIRO,
  TB_TP_CATEGORIA,
  TB_TP_ATIVIDADE,
  TP_NOTA
RESTART IDENTITY CASCADE;

INSERT INTO TB_TP_ATIVIDADE (DS_TP_ATIVIDADE) VALUES
  ('WORKSHOP'),
  ('MINICURSO');

INSERT INTO TB_TP_CATEGORIA (DS_TP_CATEGORIA) VALUES
  ('ALUNO'),
  ('COMUNIDADE');

INSERT INTO TB_TP_PARCEIRO (DS_TP_PARCEIRO) VALUES
  ('PATROCINADOR'),
  ('APOIADOR');

INSERT INTO TP_NOTA (CD_NOTA, DS_NOTA) VALUES
  (1, 'Péssimo'),
  (2, 'Ruim'),
  (3, 'Regular'),
  (4, 'Bom'),
  (5, 'Excelente');

INSERT INTO TB_ATIVIDADE (DS_TITULO, DT_INICIO, DT_FIM, ID_TP_ATIVIDADE, DS_LOCAL) VALUES
  ('Workshop de PostgreSQL', '2025-05-20 14:00', '2025-05-20 18:00', 1, 'Lab. 5 - IC-UFBA'),
  ('Minicurso de Python', '2025-06-10 09:00', '2025-06-12 12:00', 2, 'Sala 101 - IC-UFBA');

INSERT INTO TB_PARTICIPANTE (NM_PARTICIPANTE, DS_EMAIL, ID_TP_CATEGORIA) VALUES
  ('Ana Silva', 'ana.silva@ufba.br', 1),
  ('Carlos Oliveira', 'carlos.oliveira@gmail.com', 2);

INSERT INTO TB_INSTRUTOR (NM_INSTRUTOR, DS_AFILIACAO, DS_ESPECIALIDADE) VALUES
  ('Prof. João Santos', 'UFBA - Departamento de Ciência da Computação', 'Bancos de Dados'),
  ('Dra. Maria Fernandes', 'Empresa Tech Solutions', 'Inteligência Artificial');

INSERT INTO TB_PARCEIRO (NM_PARCEIRO, ID_TP_PARCEIRO, VL_CONTRIBUICAO) VALUES
  ('Oracle Academy', 1, 5000.00),
  ('Google Developer Group', 2, NULL);

INSERT INTO RL_ATIVIDADE_PARTICIPANTE (ID_ATIVIDADE, ID_PARTICIPANTE, DT_INSCRICAO, IS_PRESENCA) VALUES
  (1, 1, '2025-05-15', TRUE),
  (1, 2, '2025-05-16', TRUE);

INSERT INTO RL_ATIVIDADE_INSTRUTOR (ID_ATIVIDADE, ID_INSTRUTOR, DS_PAPEL) VALUES
  (1, 1, 'Ministrante Principal'),
  (2, 2, 'Ministrante');

INSERT INTO RL_ATIVIDADE_PARCEIRO (ID_ATIVIDADE, ID_PARCEIRO, VL_CONTRIBUICAO) VALUES
  (1, 1, 2000.00),
  (2, 2, 1000.00);

INSERT INTO TB_CERTIFICADO (CD_HASH, DT_EMISSAO, ID_ATIVIDADE, ID_PARTICIPANTE) VALUES
  ('abc123def456ghi789', '2025-05-21', 1, 1),
  ('xyz789klm456nop123', '2025-06-13', 2, 2);

INSERT INTO TB_FEEDBACK (CD_NOTA, DS_COMENTARIO, ID_ATIVIDADE, ID_PARTICIPANTE) VALUES
  (5, 'Excelente conteúdo!', 1, 1),
  (4, 'Muito bom, mas poderia ter mais exemplos.', 2, 2);
