-- Procedure 1: Cadastro de participante + inscrição
CREATE OR REPLACE PROCEDURE SP_CADASTRA_PARTICIPANTE(
    p_nome TEXT,
    p_email TEXT,
    p_id_atividade INTEGER
)
LANGUAGE plpgsql
AS $$
BEGIN
  INSERT INTO TB_PARTICIPANTE (NM_PARTICIPANTE, DS_EMAIL)
  VALUES (p_nome, p_email)
  RETURNING ID_PARTICIPANTE INTO STRICT p_id_part;

  INSERT INTO RL_PARTICIPANTE_ATIVIDADE (ID_PARTICIPANTE, ID_ATIVIDADE)
  VALUES (p_id_part, p_id_atividade);
END;
$$;

CREATE OR REPLACE PROCEDURE SP_ATUALIZA_CERTIFICADOS(
    p_id_atividade INTEGER,
    p_presenca_minima INTEGER DEFAULT 75
)
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE RL_PARTICIPANTE_ATIVIDADE
  SET IS_CERTIFICADO_EMITIDO = TRUE
  WHERE ID_ATIVIDADE = p_id_atividade
    AND VL_PRESENCA >= p_presenca_minima;

  REFRESH MATERIALIZED VIEW CONCURRENTLY MV_CERTIFICADOS_EMITIDOS;
END;
$$;
